 import 'package:iosrecal/Support/supportScreen.dart';

String HOME_PAGE = '/HomePage',
    IMAGE_SPLASH = '/ImageSplashScreen',
    VIDEO_SPALSH = '/VideoSplashScreen',
    ANIMATED_SPALSH = '/AnimatedSplashScreen',
    LOGIN_SCREEN = '/Login',
    PROFILE_SCREEN = '/Profile',
    HOME_SCREEN = '/HomeScreen',
    SOCIAL = '/HomeScreen/Social',
    BUSINESS = '/HomeScreen/Business',
    EMPLOYMENT_SUPPORT = '/HomeScreen/EmploymentSupport',
    PAY_SCREEN = '/PayScreen',
    CONTACT_US_SCREEN = '/ContactUsScreen',
    MEMBER_LINKEDIN = '/HomeScreen/EmploymentSupport/LinkedIn',
    MENTOR_GROUPS = '/HomeScreen/MentorGroups',
    WRITE_RESUME_SCREEN = '/HomeScreen/EmploymentSupport/WriteResume',
    OPEN_POSITIONS = '/HomeScreen/Employment/OpenPositions',
    ALUMNI_PLACED_SCREEN = '/HomeScreen/Employment/AlumniPlaced',
    MARKET_SURVEY='/SupportScreen/MarketSurvey',
    WRITE_TO_ADMIN='/SupportScreen/WriteAdmin',
    SEEK_GUIDANCE = '/HomeScreen/Employment/SeekGuidance',
    SOCIAL_MEDIA = '/HomeScreen/SocialMedia',
    WRITE_MENTOR='/SupportScreen/WriteToMentor',
    FEED_BACK = '/HomeScreen/SocialBusiness/Feedback',
    MEMBER_DATABASE = '/HomeScreen/SocialBusiness/Members',
    SUPPORT_SCREEN = '/HomeScreen/SupportScreen',
    TECHNICAL_SUPPORT = '/HomeScreen/SupportScreen/TechnicalSupport',
    VOLUNTEER_SUPPORT = '/HomeScreen/SupportScreen/VolunteerSupport',
    OTHER_SUPPORT = '/HomeScreen/SupportScreen/OtherSupport',
    BUSINESS_DATABASE='/HomeScreen/Business/Database', 
    DEALS_EXECUTED = '/HomeScreen/Business/Deals',
    NOTIFICATION_MENU = '/HomeScreen/Notifications';

